name: golangci-lint

on:
  push:
    branches: pandoc-golangci-lint
    paths:
      - 'golangci-lint/*'
      - '.github/workflows/golangci-lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: prepare
        id: prepare
        run: |
          REPO="ghcr.io/${{ github.repository_owner }}/golangci-lint"
          COMMIT="$(git rev-parse --short HEAD)"
          echo ::set-output name=repo::${REPO}
          echo ::set-output name=commit::${COMMIT}
      - name: docker build
        run: |
          docker build -t ${{ steps.prepare.outputs.repo }}:${{ steps.prepare.outputs.commit }} golangci-lint/
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.RELEASE_GHCR_USER_NAME }}
          password: ${{ secrets.RELEASE_GHCR_USER_TOKEN }}
      - name: docker tag and push
        run: |
          REF="${{ steps.prepare.outputs.repo }}:${{ steps.prepare.outputs.commit }}"
          TAG="$(docker run --rm --entrypoint sh ${REF} -c 'golangci-lint --version | awk "{print \$4}"')"
          docker tag ${REF} ${{ steps.prepare.outputs.repo }}:${TAG}
          docker push ${{ steps.prepare.outputs.repo }}:${TAG}
      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
